### PR TITLE
fix: prevent non-functional goals from having child goals

### LINKED ISSUE #166: Prevent non-functional goals from having child goals
Currently, it’s possible to drag a goal to become a child of a non-functional goal in the hierarchy view. This should not be allowed, since non-functional goals cannot have child goals.

### PR DESCRIPTION
**Pull request by lvqq2000**
The user won't be able to drag goals to the right sides of the non-functional goals now

closes #166

### CODE REVIEW

**Review by bggolding — CHANGES_REQUESTED** [review]

File: src/components/context/FileProvider.tsx [hunk 1]
```diff
@@ -86,8 +86,10 @@ export const NON_FUNCTIONAL_GOAL_TYPES = ["Be", "Feel", "Concern", "Who"] as con
 
 export type NonFunctionalGoalType = (typeof NON_FUNCTIONAL_GOAL_TYPES)[number];
 
-export const isNonFunctional = (label: Label): label is NonFunctionalGoalType =>
-  NON_FUNCTIONAL_GOAL_TYPES.includes(label as NonFunctionalGoalType);
+export const isNonFunctionalGoal = (
+  label: Label | undefined
+): label is NonFunctionalGoalType =>
+  !!label && NON_FUNCTIONAL_GOAL_TYPES.includes(label as NonFunctionalGoalType);
```
Comment (bggolding) [inline src/components/context/FileProvider.tsx]: Do you need the `!!label` in this test? `NON_FUNCTIONAL_GOAL_TYPES` will never include `undefined`

**Review by bggolding — APPROVED** [review]
