### PR TITLE
#235 fail to auto centred

### LINKED ISSUE #235: Graph does not auto-centre when entering the graph section for the first time
Auto-centring works when entering the graph section for the second time or later, but not on the first entry.

Steps to Reproduce

1. Click Create Model to create a default model.
2. Click Arrange Hierarchy / Render Model to enter the graph section.
3. Observe that the graph is not centred.
4. Click Arrange Hierarchy / Render Model again to re-enter the graph section.
5. Observe that the graph is now centred.

### PR DESCRIPTION
**Pull request by lvqq2000**
The graph will now be auto-centred when open graph section for the first time

closes #235

### CODE REVIEW

File: src/components/Graphs/GraphWorker.tsx [hunk 1]
```diff
@@ -589,25 +589,38 @@ const GraphWorker: React.FC<{ showGraphSection?: boolean }> = ({ showGraphSectio
     // Auto-center when goals in the canvas change (e.g. new goal added) or 
     // when entering render section (every time, not just first entry)
     useEffect(() => {
-        if (!showGraphSection || !graph || cluster.ClusterGoals.length === 0) return;
+        if (!showGraphSection || !graph || !divGraph.current) return;
 
-        let attempts = 0;
-        const maxAttempts = 20;
+        const container = divGraph.current;
+        let lastBounds: { width: number; height: number } | null = null;
```
Comment (bggolding) [inline src/components/Graphs/GraphWorker.tsx]: Please remove spaces inside braces:
`        let lastBounds: {width: number; height: number} | null = null;`

File: src/components/Graphs/GraphWorker.tsx [hunk 2]
```diff
@@ -589,25 +589,38 @@ const GraphWorker: React.FC<{ showGraphSection?: boolean }> = ({ showGraphSectio
...
+        const observer = new ResizeObserver(() => {
             const bounds = graph.getGraphBounds();
+            if (!bounds) return;
 
-            if (bounds && bounds.width > 0 && bounds.height > 0) {
-                recentreView(graph);
-            } else if (attempts < maxAttempts) {
-                attempts++;
-                requestAnimationFrame(tryCenter);
+            const { width, height } = bounds;
```
Comment (bggolding) [inline src/components/Graphs/GraphWorker.tsx]: Again, please remove spaces inside braces:
`const {width, height} = bounds;`

File: src/components/Graphs/GraphWorker.tsx [hunk 3]
```diff
@@ -589,25 +589,38 @@ const GraphWorker: React.FC<{ showGraphSection?: boolean }> = ({ showGraphSectio
...
+            if (width > 0 && height > 0) {
+
+                // Check if bounds are stable (same as last frame)
+                if (lastBounds && lastBounds.width === width && lastBounds.height === height) {
+                    // Graph is finalized -> center and stop observing
+                    recentreView(graph);
+                    observer.disconnect();
+                } else {
+                    // Store bounds for next frame
+                    lastBounds = { width, height };
```
Comment (bggolding) [inline src/components/Graphs/GraphWorker.tsx]: Ditto.

File: src/components/Graphs/GraphWorker.tsx (hunk 1 above)
Comment (bggolding) [reply src/components/Graphs/GraphWorker.tsx]: Shouldn’t that be?:
```typescript
 let lastBounds: {width: number, height: number} | null = null;
```
(comma instead of semicolon)

**Review by bggolding — APPROVED** [review]
